services:
  db:
    image: postgres:16
    container_name: ad_pg
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: DeinStarkesPasswort
      POSTGRES_DB: appdb
      TZ: UTC
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d:ro

  adminer:
    image: adminer
    container_name: ad_adminer
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
